site_name: Otterdog configuration @ eclipse-ankaios
site_description: Otterdog configuration @ eclipse-ankaios
strict: false

site_url: https://eclipse-ankaios.github.io/.eclipsefdn/

repo_name: eclipse-ankaios/.eclipsefdn
repo_url: https://github.com/eclipse-ankaios/.eclipsefdn/

docs_dir: ./docs
site_dir: ./_site

theme:
  name: 'material'
  custom_dir: docs/overrides
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - macros

nav:
  - Overview: index.md
  - playground.md

watch: []

extra:
  org_id: eclipse-ankaios

extra_css:
  - stylesheets/extra.css
